export default [
  {
    id: 1,
    type: 1,
    title: {
      'zh-CN': '蒂姆·库克回复了你的邮件',
      'en-US': 'Tim Cook replied to your email',
    },
    color: '#1890ff',
    icon: 'D',
    time: '2019-05-08 14:33:18',
    isReaded: false,
  },
  {
    id: 2,
    type: 1,
    title: {
      'zh-CN': '乔纳森·伊夫邀请你参加会议',
      'en-US': 'Jonathan Yves invites you to the meeting',
    },
    color: '#52c41a',
    icon: 'G',
    time: '2019-05-08 14:33:18',
    isReaded: true,
  },
  {
    id: 3,
    type: 1,
    title: {
      'zh-CN': '沃兹尼亚克已批准了你的休假申请',
      'en-US': 'Wozniak has approved your vacation application',
    },
    color: '#faad14',
    icon: 'M',
    time: '2019-05-08 14:33:18',
    isReaded: true,
  },
  {
    id: 4,
    type: 1,
    title: {
      'zh-CN': '史蒂夫·乔布斯收藏了你的文章',
      'en-US': 'Steve Jobs has collected your articles',
    },
    color: '#f5222d',
    icon: 'N',
    time: '2019-05-08 14:33:18',
    isReaded: true,
  },
  {
    id: 5,
    type: 1,
    title: {
      'zh-CN': '比尔·费尔南德斯通过了你的好友申请',
      'en-US': 'Bill Fernandez approved your friend application',
    },
    color: '#1890ff',
    icon: 'P',
    time: '2019-05-08 14:33:18',
    isReaded: true,
  },
  {
    id: 6,
    type: 2,
    title: {
      'zh-CN': '史蒂夫·乔布斯 关注了你',
      'en-US': 'Steve Jobs followed you',
    },
    color: '#52c41a',
    icon: 'A',
    time: '2019-05-08 14:33:18',
    isReaded: false,
  },
  {
    id: 7,
    type: 2,
    title: {
      'zh-CN': '斯蒂夫·沃兹尼亚克 关注了你',
      'en-US': 'Steve Wozniak followed you',
    },
    color: '#1890ff',
    icon: 'M',
    time: '2019-05-08 14:33:18',
    isReaded: false,
  },
  {
    id: 8,
    type: 2,
    title: {
      'zh-CN': '乔纳森·伊夫 关注了你',
      'en-US': 'Jonathan Ive followed you',
    },
    color: '#faad14',
    icon: 'P',
    time: '2019-05-08 14:33:18',
    isReaded: true,
  },
  {
    id: 9,
    type: 2,
    title: {
      'zh-CN': '蒂姆·库克 关注了你',
      'en-US': 'Tim Cook followed you',
    },
    color: '#f5222d',
    icon: 'N',
    time: '2019-05-08 14:33:18',
    isReaded: true,
  },
  {
    id: 10,
    type: 2,
    title: {
      'zh-CN': '比尔·费尔南德斯 关注了你',
      'en-US': 'Bill Fernandez followed you',
    },
    color: '#1890ff',
    icon: 'M',
    time: '2019-05-08 14:33:18',
    isReaded: true,
  },
  {
    id: 11,
    type: 3,
    title: {
      'zh-CN': '2021 上半年 OKR',
      'en-US': 'First half of 2021 OKR',
    },
    description: {
      'zh-CN': '需要在 2021-06-14 之前完成',
      'en-US': 'Need to be completed by 2021-06-14',
    },
    color: '#1890ff',
    icon: 'P',
    time: '2019-05-08 14:33:18',
    isReaded: false,
  },
  {
    id: 12,
    type: 3,
    title: {
      'zh-CN': '公孙离的面试评审',
      'en-US': "Gongsunli's interview review",
    },
    description: {
      'zh-CN': '需要在 2021-06-14 之前完成',
      'en-US': 'Need to be completed by 2021-06-14',
    },
    color: '#52c41a',
    icon: 'M',
    time: '2019-05-08 14:33:18',
    isReaded: true,
  },
  {
    id: 11,
    type: 3,
    title: {
      'zh-CN': '2021 上半年 OKR',
      'en-US': 'First half of 2021 OKR',
    },
    description: {
      'zh-CN': '需要在 2021-06-14 之前完成',
      'en-US': 'Need to be completed by 2021-06-14',
    },
    color: '#f5222d',
    icon: 'A',
    time: '2019-05-08 14:33:18',
    isReaded: false,
  },
  {
    id: 12,
    type: 3,
    title: {
      'zh-CN': '公孙离的面试评审',
      'en-US': "Gongsunli's interview review",
    },
    color: '#1890ff',
    icon: 'N',
    description: {
      'zh-CN': '需要在 2021-06-14 之前完成',
      'en-US': 'Need to be completed by 2021-06-14',
    },
    time: '2019-05-08 14:33:18',
    isReaded: true,
  },
];
