export default [
  {
    id: 1,
    name: 'admin',
    nickname: 'John Doe',
    password: '123456',
    role: 'admin',
    permissions: [
      'view:404',
      'view:403',
      'view:login',
      'view:index',
      'view:personal',
      'view:personal_info',
      'view:personal_setting',
      'view:dashboard',
      'view:dashboard_overview',
      'view:dashboard_workplace',
      'view:form',
      'view:form_basic',
      'view:form_step',
      'view:result',
      'view:result_success',
      'view:result_fail',
      'view:components',
      'view:components_phone',
      'view:components_otp-send',
      'view:components_otp-input',
      'view:components_formatted',
      'view:components_scroll',
      'view:components_wangeditor',
      'view:components_markdown',
      'view:authority',
      'view:authority_route',
      'view:authority_menu',
      'view:authority_operate',
      'add:authority_operate',
      'delete:authority_operate',
      'update:authority_operate',
    ],
  },
  {
    id: 2,
    name: 'user',
    nickname: 'Christina',
    password: '123456',
    role: 'user',
    permissions: [
      'view:404',
      'view:403',
      'view:login',
      'view:index',
      'view:personal',
      'view:personal_info',
      'view:personal_setting',
      'view:dashboard',
      'view:dashboard_overview',
      'view:dashboard_workplace',
      'view:form',
      'view:form_basic',
      'view:form_step',
      'view:result',
      'view:result_success',
      'view:result_fail',
      'view:components',
      'view:components_phone',
      'view:components_otp-send',
      'view:components_otp-input',
      'view:components_formatted',
      'view:components_scroll',
      'view:components_wangeditor',
      'view:components_markdown',
      'view:authority',
      'view:authority_operate',
    ],
  },
];
