export default [
  {
    id: 1,
    name: 'admin',
    nickname: 'John Doe',
    password: '123456',
    role: 'admin',
    permissions: [
      'view:404',
      'view:403',
      'view:login',
      'view:index',
      'view:personal',
      'view:personal_info',
      'view:personal_setting',
      'view:dashboard',
      'view:dashboard_overview',
      'view:dashboard_workplace',
      'view:form',
      'view:form_basic',
      'view:form_step',
      'view:result',
      'view:result_success',
      'view:result_fail',
    ],
  },
  {
    id: 2,
    name: 'user',
    nickname: 'Christina',
    password: '123456',
    role: 'user',
    permissions: [
      'view:404',
      'view:403',
      'view:login',
      'view:index',
      'view:personal',
      'view:personal_info',
      'view:personal_setting',
      'view:dashboard',
      'view:dashboard_overview',
      'view:dashboard_workplace',
      'view:form',
      'view:form_basic',
      'view:form_step',
      'view:result',
      'view:result_success',
      'view:result_fail',
    ],
  },
];
